import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'uz_UZ': {
      'name':'Dilshodjon',
      'surname':'Haydarov',
      'Familiya':'Familiya',
      'Ha':'Ha',
      'yo‘q':'yo‘q',
      'Bekor qilish':'Bekor qilish',
      'Tayyor':'Tayyor',
      'Kiriting':'Kiritng',
      'Salom':'Salom',
      'Yangi bilimlarni o‘rganishga tayyormisiz?':'Yangi bilimlarni o‘rganishga tayyormisiz?',
      'Ma’lumotlar yo’q':'Ma’lumotlar yo’q',
      'Batafsil ko‘rish':'Batafsil ko‘rish',
      'Fanlar':'Fanlar',
      'Sozlamalar':'Sozlamalar',
      'Dastur haqida':'Dastur haqida',
      'Test natijalari':'Test natijalari',
      'To’lovlar tarixi':'To’lovlar tarixi',
      'Tilni o‘zgartirish':'Tilni o‘zgartirish',
      'Ilovadan chiqish':'Ilovadan chiqish',
      'ko‘rish':'Ko‘rish',
      'so‘m':'so‘m',
      'Xatolik':'Xatolik',
      'Bu kitobni o‘qish uchun to‘lov qiling':'Bu kitobni o‘qish uchun to‘lov qiling',
      'Ma’lumotlarni yangilash uchun tashlang':'Ma’lumotlarni yangilash uchun tashlang',
      'Ehhh nimadir xato ketdi':'Ehhh nimadir xato ketdi',
      'Ma’lumotlar yangilandi':'Ma’lumotlar yangilandi',
      'Dasturga kirish':'Dasturga kirish',
      'Google akkaunt orqali dasturga kiring':'Google akkaunt orqali dasturga kiring',
      'Google orqali kirish':'Google orqali kirish',
      'Apple orqali kirish':'Apple orqali kirish',
      'Savollar':'Savollar',
      'Barcha imkoniyatlardan foydalanish uchun ilovaning to‘liq versiyasini sotib oling':'Barcha imkoniyatlardan foydalanish uchun ilovaning to‘liq versiyasini sotib oling',
      'To‘lov miqdori':'To‘lov miqdori',
      'To‘lash':'To‘lash',
      'To‘lov qilish':'To‘lov qilish',
      'Yakunlash':'Yakunlash',
      'Avvalgisi':'Avvalgisi',
      'Keyingisi':'Keyingisi',
      'Testni boshlash':'Testni boshlash',
      'daqiqa':'daqiqa',
      'ttest':'ta test',
      'sinf':'sinf',
      'To‘lov amalga oshirilgan':'To‘lov amalga oshirilgan',
      'To‘lov amalga oshirilmagan':'To‘lov amalga oshirilmagan',
      'Test yakunlandi':'Test yakunlandi',
      'Tabriklaymiz! Siz testni yakunladingiz. Natijalar saqlandi':'Tabriklaymiz! Siz testni yakunladingiz. Natijalar saqlandi.',
      'Server bilan aloqa yo‘q':'Server bilan aloqa yo‘q',
      'Qayta yuklash':'Qayta yuklash',
      'Dasturdan chiqasizmi?':'Dasturdan chiqasizmi?',
      'Dasturdan chiqqaningdan so‘ng qayta kirishingiz mumkin!':'Dasturdan chiqqaningdan so‘ng qayta kirishingiz mumkin!',
      'Chiqish':'Chiqish',
      'Bildirishnomalar':'Bildirishnomalar',
      'Javob': 'Javob',
      'Savol': 'Savol',
      'Hisobni o‘chirish':'Hisobni o‘chirish',
      'Muvaffaqiyatli':'Muvaffaqiyatli',
      'Hisob muvaffaqiyatli o‘chirildi': 'Hisob muvaffaqiyatli o‘chirildi',
      'Hisob o‘chirilmadi': 'Hisob o‘chirilmadi',
      'delete log': 'Hisobingizni o‘chirish orqali barcha ma’lumotlaringiz, sozlamalaringiz va faoliyat tarixi butunlay yo‘q qilinadi. Ushbu amalni bekor qilib bo‘lmaydi.',
    },
    'ru_RU': {
      'name':'Дилшоджон',
      'surname':'Хайдаров',
      'Familiya':'Фамилия',
      'Ha':'Да',
      'yo‘q':'Нет',
      'Bekor qilish':'Отменить',
      'Tayyor':'Готово',
      'Kiriting':'Введите',
      'Salom':'Привет',
      'Yangi bilimlarni o‘rganishga tayyormisiz?':'Хотите изучать новые знания?',
      'Ma’lumotlar yo’q':'Нет данных',
      'Batafsil ko‘rish':'Подробнее',
      'Fanlar':'Предметы',
      'Sozlamalar':'Настройки',
      'Dastur haqida':'О приложении',
      'Test natijalari':'Результаты тестов',
      'To’lovlar tarixi':'История платежей',
      'Tilni o‘zgartirish':'Изменить язык',
      'Ilovadan chiqish':'Выйти',
      'ko‘rish':'Посмотреть',
      'so‘m':'сум',
      'Xatolik':'Ошибка',
      'Bu kitobni o‘qish uchun to‘lov qiling':'Оплатите чтение этого книги',
      'Ma’lumotlarni yangilash uchun tashlang':'Обновите информацию',
      'Ehhh nimadir xato ketdi':'Что-то пошло не так',
      'Ma’lumotlar yangilandi':'Информация обновлена',
      'Dasturga kirish':'Вход',
      'Google akkaunt orqali dasturga kiring':'Вход через аккаунт Google',
      'Google orqali kirish':'Вход через Google',
      'Apple orqali kirish':'Вход через Apple',
      'Savollar':'Вопросы',
      'Barcha imkoniyatlardan foydalanish uchun ilovaning to‘liq versiyasini sotib oling':'Купите полную версию приложения для доступа ко всем ресурсам',
      'To‘lov miqdori':'Цена',
      'To‘lash':'Оплатить',
      'To‘lov qilish':'Оплатить',
      'Yakunlash':'Завершить',
      'Avvalgisi':'Назад',
      'Keyingisi':'Продолжить',
      'Testni boshlash':'Начать тест',
      'daqiqa':'секунд',
      'ttest':'тестов',
      'sinf':'класс',
      'To‘lov amalga oshirilgan':'Платёж выполнен',
      'To‘lov amalga oshirilmagan':'Платёж не выполнен',
      'Test yakunlandi':'Тест завершен',
      'Tabriklaymiz! Siz testni yakunladingiz. Natijalar saqlandi':'Спасибо! Вы закончили тест. Результаты сохранены',
      'Server bilan aloqa yo‘q':'Сервер недоступен',
      'Qayta yuklash':'Перезагрузить',
      'Dasturdan chiqasizmi?':'Выйти из приложения?',
      'Dasturdan chiqqaningdan so‘ng qayta kirishingiz mumkin!':'Выйти из приложения, чтобы заново войти!',
      'Chiqish':'Выйти',
      'Bildirishnomalar':'Уведомления',
      'Javob': 'Ответ',
      'Savol': 'Вопрос',
      'Hisobni o‘chirish':'Удалить аккаунт',
      'Muvaffaqiyatli':'Успешно',
      'Hisob muvaffaqiyatli o‘chirildi': 'Аккаунт успешно удалён',
      'Hisob o‘chirilmadi': 'Аккаунт не удалён',
      'delete log': 'При удалении вашей учетной записи все ваши данные, настройки и история активности будут полностью удалены. Это действие невозможно отменить.',

    }
  };
}